# Copyright (c) IBM Corporation 2020

---
galaxy_info:
  author: Yang Cao <caoy@cn.ibm.com>, Yun Juan Yang <yunyyang@cn.ibm.com>
  description: Ansible role to complete a z/OS workflow forcibly or idempotently.
  company: IBM
  min_ansible_version: 2.9
  galaxy_tags:
    - ibm
    - z
    - zos
    - zosmf
    - workflow
  license:
    - Apache-2.0
  platforms:
    - name: All
dependencies: []
