# Copyright (c) IBM Corporation 2020 
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
- name: Query the contents of each spool file - Send https request
  uri:
    url: "{{ file_item['records-url'] }}?mode=text&research={{ job_search_output | urlencode }}\
          &insensitive={{ job_search_output_insensitive }}&maxreturnsize={{ job_search_output_maxreturnsize }}"
    method: GET
    return_content: yes
    headers:
      X-CSRF-ZOSMF-HEADER: "TEST"
    user: "{{ user }}"
    password: "{{ password }}"
    client_cert: "{{ crt }}"
    client_key: "{{ key }}"
    force_basic_auth: yes
    status_code: "200"
    validate_certs: no
  delegate_to: localhost
  register: record_result
  failed_when: no

- include_tasks: handle_request_error.yml
  vars:
    expect_rcode: 200
    result: "{{ record_result }}"

- name: Query the contents of each spool file - Parse the matched contents - Step 1 Turn into list
  set_fact:
    matched_list: "{{ record_result.content | regex_findall('.*\n') }}"
    matched_list_parse: []

- name: Query the contents of each spool file - Parse the matched contents - Step 2 Remove '\n'
  set_fact:
    matched_list_parse: "{{ matched_list_parse + [item | regex_replace('\n', '')] }}"
    job_matched_contents_found: True
  loop: "{{ matched_list }}"

- name: Query the contents of each spool file - Parse the matched contents - Step 3 Combine into job_matched_contents
  set_fact:
    job_matched_contents: "{{ job_matched_contents | combine({ file_item.ddname: matched_list_parse }) }}"