# Copyright (c) IBM Corporation 2020 
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
- name: Check whether the workflow instance already exists
  workflow:
    action: "compare"
    zmf_host: "{{ zmf_host }}"
    zmf_port: "{{ zmf_port | default(-1) }}"
    zmf_user: "{{ zmf_user | default() }}"
    zmf_password: "{{ zmf_password | default() }}" 
    zmf_crt: "{{ zmf_crt | default() }}" 
    zmf_key: "{{ zmf_key | default() }}" 
    zos_workflow_name: "{{ zos_workflow_name }}"
    zos_workflow_file: "{{ zos_workflow_file | default() }}"
    zos_workflow_host: "{{ inventory_hostname | default() }}"
    zos_workflow_owner: "{{ zos_workflow_owner | default() }}"
    zos_workflow_file_system: "{{ zos_workflow_file_system | default() }}"
    zos_workflow_vars_file: "{{ zos_workflow_vars_file | default() }}"
    zos_workflow_vars: "{{ zos_workflow_vars | default({}) }}"
    zos_workflow_resolve_global_conflict_by_using: "{{ zos_workflow_resolve_global_conflict_by_using | default() }}"
    zos_workflow_comments: "{{ zos_workflow_comments | default() }}"
    zos_workflow_assign_to_owner: "{{ zos_workflow_assign_to_owner | default(True) }}"
    zos_workflow_access_type: "{{ zos_workflow_access_type | default() }}"
    zos_workflow_account_info: "{{ zos_workflow_account_info | default() }}"
    zos_workflow_job_statement: "{{ zos_workflow_job_statement | default() }}"
    zos_workflow_delete_completed_jobs: "{{ zos_workflow_delete_completed_jobs | default(False) }}"
    zos_workflow_category: "{{ zos_workflow_category | default() }}"
    zos_workflow_vender: "{{ zos_workflow_vender | default() }}"
  delegate_to: localhost
  register: compare_result
  when: force_complete != true

- name: Delete the existing workflow instance if force complete or it has different definition file, variables or properties
  workflow:
    action: "delete"
    zmf_host: "{{ zmf_host }}"
    zmf_port: "{{ zmf_port | default(-1) }}"
    zmf_user: "{{ zmf_user | default() }}"
    zmf_password: "{{ zmf_password | default() }}" 
    zmf_crt: "{{ zmf_crt | default() }}" 
    zmf_key: "{{ zmf_key | default() }}" 
    zos_workflow_name: "{{ zos_workflow_name }}"
    zos_workflow_key: "{{ compare_result.exist_workflow_key | default() }}"
  delegate_to: localhost
  register: delete_result
  when: (force_complete == true) or 
        (compare_result.exist_workflow_key != '' and compare_result.same_workflow_instance == false)

- name: Reset exist_workflow_key if the existing workflow instance is deleted
  set_fact:
    compare_result: {'exist_workflow_key':'', 'workflow_completed':false}
  when: (force_complete != true) and (delete_result.changed == true)

- name: Create the workflow instance if not exist and start it
  workflow:
    action: "start"
    zmf_host: "{{ zmf_host }}"
    zmf_port: "{{ zmf_port | default(-1) }}"
    zmf_user: "{{ zmf_user | default() }}"
    zmf_password: "{{ zmf_password | default() }}" 
    zmf_crt: "{{ zmf_crt | default() }}" 
    zmf_key: "{{ zmf_key | default() }}" 
    zos_workflow_name: "{{ zos_workflow_name }}"
    zos_workflow_file: "{{ zos_workflow_file | default() }}"
    zos_workflow_host: "{{ inventory_hostname | default() }}"
    zos_workflow_owner: "{{ zos_workflow_owner | default() }}"
    zos_workflow_file_system: "{{ zos_workflow_file_system | default() }}"
    zos_workflow_vars_file: "{{ zos_workflow_vars_file | default() }}"
    zos_workflow_vars: "{{ zos_workflow_vars | default({}) }}"
    zos_workflow_resolve_global_conflict_by_using: "{{ zos_workflow_resolve_global_conflict_by_using | default() }}"
    zos_workflow_comments: "{{ zos_workflow_comments | default() }}"
    zos_workflow_assign_to_owner: "{{ zos_workflow_assign_to_owner | default(True) }}"
    zos_workflow_access_type: "{{ zos_workflow_access_type | default() }}"
    zos_workflow_account_info: "{{ zos_workflow_account_info | default() }}"
    zos_workflow_job_statement: "{{ zos_workflow_job_statement | default() }}"
    zos_workflow_delete_completed_jobs: "{{ zos_workflow_delete_completed_jobs | default(False) }}"
    zos_workflow_resolve_conflict_by_using: "{{ zos_workflow_resolve_conflict_by_using | default() }}"
    zos_workflow_step_name: "{{ zos_workflow_step_name | default() }}"
    zos_workflow_perform_subsequent: "{{ zos_workflow_perform_subsequent | default(True) }}"
    zos_workflow_notification_url: "{{ zos_workflow_notification_url | default() }}"
    zos_workflow_key: "{{ compare_result.exist_workflow_key | default() }}"
  delegate_to: localhost
  register: start_result
  when: (force_complete == true) or 
        ('workflow_completed' not in compare_result or compare_result.workflow_completed == false)

- name: Priodically check status of the workflow instance and return final result
  workflow:
    action: "check"
    zmf_host: "{{ zmf_host }}"
    zmf_port: "{{ zmf_port | default(-1) }}"
    zmf_user: "{{ zmf_user | default() }}"
    zmf_password: "{{ zmf_password | default() }}" 
    zmf_crt: "{{ zmf_crt | default() }}" 
    zmf_key: "{{ zmf_key | default() }}" 
    zos_workflow_key: "{{ start_result.workflow_key | default(compare_result.exist_workflow_key) }}"
  delegate_to: localhost
  register: result
  until: (result is failed) or (result.waiting == false)
  retries: "{{ complete_check_times }}"
  delay: "{{ complete_check_delay }}"

- name: Fail if the workflow instance is not completed
  fail:
    msg: "{{ result.message }}"
  when: result.completed == false