# Copyright (c) IBM Corporation 2020

---
galaxy_info:
  author: Yang Cao <caoy@cn.ibm.com>, Yun Juan Yang <yunyyang@cn.ibm.com>
  description: Ansible role to query a job running on z/OS, check its return code and user specified content from spool files.
  company: IBM
  min_ansible_version: 2.9
  galaxy_tags:
    - ibm
    - z
    - zos
    - zosmf
    - job
  license:
    - Apache-2.0
  platforms:
    - name: GenericLinux
      versions:
      - all
dependencies: []
